### ISSUE TITLE
Jekyll very slow on MacOS

### ISSUE THREAD

**Issue by git-no** [envygeeks/jekyll-docker#214]
## Problem
Jekyll hangs at start, meaning loading jekyll is very slow on MacOS (approx > 30sec).
It appears every time jekyll command is used.

### Environment
- MacOS latest version: 10.13.3
- Docker latest version: 17.12.0-ce-mac55 (23011)
- Jekyll-Docker latest version: Build 1ae4979  
- Jekyll latest version: 3.7.3, standard Jekyll installation, no additional gems.
- Docker run with volume

## Steps to Reproduce
Run Docker with volume configuration as described within the README of jekyll-docker
```
docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -it -p 4000:4000 -p 35729:35729 jekyll/jekyll:3.7.3 jekyll b
```
or 
```
docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -it -p 4000:4000 -p 35729:35729 jekyll/jekyll:3.7.3 bash
jekyll b
```

## Potential Reason
After some research it seams to me the reason is **docker.com.osxfs**.
MacOS users describe file access with docker volumes on MacOS are very slow.  
Proof: with this command (without volume configuration) the ```jekyll``` command is executed immediately
```
docker run --rm -it jekyll/jekyll:3.7.3 jekyll
```

## Potential Solution
This is the best solution description I found about the Docker issue of slow shared file access and a suggestion of a solution: [How to speed up shared file access in Docker for Mac](https://medium.freecodecamp.org/speed-up-file-access-in-docker-for-mac-fbeee65d0ee7)

This improved the response / loading time of the ```jekyll``` command too but not so much (approx 15 sec), so it is not satisfying but it is a well problem description by Docker: [Performance tuning for volume mounts ](https://docs.docker.com/docker-for-mac/osxfs-caching/#consistent) .

## Expected
Faster, instance loading time of the ```jeykll``` command on MacOS with volumen configuration out of the box with jekyll-docker. 

Thank you for consideration and by the way thank you for sharing your jekyll-docker repository.

**Comment by git-no** [comment]
I was able to speed up the ```jekyll```command, does take only one second to start with [docker-sync](https://github.com/EugenMayer/docker-sync). The bummer is docker-sync needs a dedicated container to run.

This is a config of docker-sync.yml:
```yaml
version: "2"

options:
  verbose: true
  max-attempt: 30
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  vendor-bundle-sync: # tip: add -sync and you keep consistent names as a convention
    src: './vendor/bundle'
    sync_strategy: 'unison'
    sync_excludes: ['ignored_folder', '.ignored_dot_folder']
    sync_args:
      - "-prefer newer"
      - "-ignore='Path .git'"
      - "-ignore='BelowPath .git'"
```
and **docker run** 
```
docker run --rm --volume="$PWD:/srv/jekyll" -v "vendor-bundle-sync:/usr/local/bundle" -it -p 4000:4000 -p 35729:35729 jekyll/jekyll:3.7.3 bash
```
