### ISSUE TITLE
Error trying to run site using docker compose file

### ISSUE THREAD

**Issue by kyleect** [envygeeks/jekyll-docker#215]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [x] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [ ] I Am on macOS

## Description

I am running in to an error trying to run the docker compose file listed in the readme. It was a preexisting jekyll blog I'm trying to dockertize.

```
version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
```

## Steps

- Copy docker compose contents in to docker-compose.yml
- `docker-compose run site`

## Output

> ERROR: YOUR SITE COULD NOT BE BUILT:
> ------------------------------------
> Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.3.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.

## Expected

The site to build and be served
