### ISSUE TITLE
Caching fails on Gitlab CI

### ISSUE THREAD

**Issue by iSDP** [envygeeks/jekyll-docker#221]
## Description

I tried to enable caching for `/usr/local/bundles`
This did not work.

## Steps
```yaml
stages:
  - build
  - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /usr/local/bundle

build-jekyll:
  stage: build
  image: jekyll/builder
  artifacts:
    untracked: true
  script:
    - jekyll build

pages:
  stage: deploy
  image: ruby
  dependencies:
  - build-jekyll
  script:
    - mv _site/ public/
  artifacts:
    paths:
    - public
```
- Enable caching
- Run pipeline

## Output

```
Creating cache master...
WARNING: /usr/local/bundle: no matching files      
Created cache
```

## Expected

Cache being stored

## How to fix

Use a path in the current working directory (.local?)
