### ISSUE TITLE
Can i add it gitlab-ci.yml

### ISSUE THREAD

**Issue by bsde1245** [envygeeks/jekyll-docker#249]
I deploy jekyll to gitlab. To fasten build for each commit, where to add your code? Can i add it to gitlab-ci.yml?
```
export JEKYLL_VERSION=3.8
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  --volume="$PWD/vendor/bundle:/usr/local/bundle" \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  jekyll build
```

**Comment by ffes** [comment]
In your `.gitlab-ci.yml` simply use the line `image: jekyll/jekyll` in your build stage

See for example: https://gitlab.com/ffes/ffes.gitlab.io/blob/master/.gitlab-ci.yml

**Comment by envygeeks** [comment]
That’s a good example. I don’t really know much about Gitlab, and I do not interject myself in user setups. Sorry.

**Comment by bsde1245** [comment]
can i cache the build?

**Comment by envygeeks** [comment]
Caching the build is up to the CI see https://docs.gitlab.com/ee/ci/caching/ for more information.

**Comment by bsde1245** [comment]
Please give some advice. My `ci.yml` is,  
```
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - export LC_ALL="C.UTF-8"
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
```
I used artifacts, So I think I need to remove it right? Also do I need to remove,   

```
test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

```
to fast the build process. Also I think I need to cache bundle not npm, right? NPM cache example listed in your given link, like  
```
#
# https://gitlab.com/gitlab-org/gitlab-ce/tree/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml
#
image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

test_async:
  script:
  - node ./specs/start.js ./specs/async.spec.js
```
But how to cache bundle?
