### ISSUE TITLE
Get "library.rb:112: [BUG] Illegal instruction at ..." when running the jekyll:4

### ISSUE THREAD

**Issue by joshwapohlmann** [envygeeks/jekyll-docker#261]
I get the following error when trying to use the docker image on a **Intel(R) Celeron(R) CPU J3455** with **4.15.0-66-generic x86_64 GNU/Linux Ubuntu**.

```bash
$ docker pull jekyll/jekyll:4
$ docker run -i -t --rm -v /tmp/blog/:/srv/jekyll jekyll/jekyll:4 jekyll new .
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
/usr/gem/gems/ffi-1.11.1/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007fd8781336e2
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
```

Since the backtrace is rediculously long [here is the pastebin](https://pastebin.com/RM8NEcyU)

**Comment by joshwapohlmann** [comment]
This could be a hint: https://northsail.io/articles/ruby-sassc-illegal-instruction

**Comment by joshwapohlmann** [comment]
Running [jekyll:3](https://hub.docker.com/layers/jekyll/jekyll/3/images/sha256-9521c8aae4739fcbc7137ead19f91841b833d671542f13e91ca40280e88d6e34) works fine!

**Comment by joshwapohlmann** [comment]
It will yields the fitting "warning"
```
 Bundler: Post-install message from sass:
  Bundler:
  Bundler: Ruby Sass has reached end-of-life and should no longer be used.
  Bundler:
  Bundler: * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  Bundler: primary implementation: https://sass-lang.com/install
  Bundler:
  Bundler: * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  Bundler: sassc gem: https://github.com/sass/sassc-ruby#readme
  Bundler:
  Bundler: * For more details, please refer to the Sass blog:
  Bundler: https://sass-lang.com/blog/posts/7828841
```
