### ISSUE TITLE
file changes on host system not picked up by `jekyll serve --watch`

### ISSUE THREAD

**Issue by jimklo** [envygeeks/jekyll-docker#281]
I have a fairly simple `docker-compose.yml` file:

```yaml
version: "3.0"

services:
  dev:
    image: jekyll/builder
    command: ["jekyll", "serve", "--incremental", "--watch", "--verbose" ]
    ports: 
      - "4000:4000"
    volumes: 
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
```

As I'm currently using Windows 10, I also have a `.env` file that defines `PWD=c:\source\website`.

Running `docker-compose up` works as expected, however any changes to files made on the host that should trigger a recompile don't work.  It's unclear if this is a docker, jekyll, or jekyll-docker issue - however since it seems the most productive use case of jekyll-docker is it's use as easily portable dev environment.  If I exec a bash shell inside the container and `touch` a modified file, the recompile is triggered.
