### ISSUE TITLE
Doesn't install system packages

### ISSUE THREAD

**Issue by DDoerner** [envygeeks/jekyll-docker#309]
I use the image `jekyll/builder:4.2.0` and try to install additional system packages using an `.apk` file as described in the docs, but it fails every time with a warning message that the constraints could not be satisfied. I am unexperienced with Alpine Linux, so I don't know whether I've made a mistake on my end or whether it might be a bug.

I've checked with https://pkgs.alpinelinux.org already that both packages exist for the branch and architecture that its looking for, so I don't understand why it shouldn't be able to find and install the packages.

Any help would be appreciated.

`docker-compose.yml`
```
version: '3.3'
services:
  jekyll:
    image: jekyll/builder:4.2.0
    command: jekyll serve --livereload --verbose --incremental --force_polling --trace
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
```

`.apk`
```
vips
libpng
```

Log
```
$ docker compose up
[+] Running 2/2
 - Network "website_default"   Created                                                                                                                                2.4s 
 - Container website_jekyll_1  Created                                                                                                                                0.3s 
Attaching to jekyll_1
jekyll_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
jekyll_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
jekyll_1  | ERROR: unsatisfiable constraints:
 (missing):   libpng
]ekyll_1  |     required by: world[libpng
 (missing):   vips
]ekyll_1  |     required by: world[vips
jekyll_1 exited with code 2
```
